version: "3.7"
services:
  commandscom:
    image: dtannen/commandscom
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
  cors-anywhere:
    image: redocly/cors-anywhere
    environment:
      - CORSANYWHERE_WHITELIST=http://localhost:3000,https://localhost:3000,https://commands.com,http://commands.com
    ports:
      - "8080:8080"
    expose:
      - '8080'
